# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev/*

jobs:

- template: AgoraLive-Android/build-templates/build-release.yml
  parameters:
    project: 'AgoraLive-Android'
    name: 'AgoraLive_Android'
    
- template: AgoraLive-iOS/Build/azure/build.yml
  parameters:
    displayName: 'AgoraLive_iOS_Debug'
    mode: 'Debug'
    upload: 0
    bugly: 0
    
- template: AgoraLive-iOS/Build/azure/build.yml
  parameters:
    displayName: 'AgoraLive_iOS_QA_Dev'
    mode: 'QA-Dev'
    upload: 1
    bugly: 1
